openapi: 3.0.0
info:
  title: 'app'
  version: '1.0'
paths:
  /test:
    get:
      operationId: success
      parameters:
        - name: int
          in: query
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  int:
                    type: integer
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: key
      in: query
      x-apikeyInfoFunc: security.apikey_info
      
security:
  - api_key: []



